services:
  mariadb:
    image: mariadb:11.2
    container_name: mariadb
    hostname: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: article
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - mariadbnet

  nifi:
    build:
      context: ./Nifi
      dockerfile: Dockerfile
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      # Минимальная длина пароля - 12 символов
      - SINGLE_USER_CREDENTIALS_PASSWORD=password12345
    volumes:
      - ./nifi/drivers:/opt/nifi/nifi-current/drivers
      - ./result:/result
    networks:
      - elastic
      - mariadbnet
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic_password
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.10
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana_password
    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  esdata:
  mariadb-data:

networks:
  elastic:
    name: elastic
    driver: bridge
  mariadbnet:
    name: mariadbnet